apiVersion: apps/v1
kind: Deployment
metadata:
  name: crashloop-example
  labels:
    app: crashlooplearning
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crashlooplearning
  template:
    metadata:
      labels:
        app: crashlooplearning
    spec:
      containers:
      - name: crashlooplearning
        image: yogeshrathod1137/crashlooptest:v2
        ports:
        - containerPort: 8000
        resources:
         limits:
          cpu: "25m"
          memory: "25Mi"
         
